config/routes.rb
Rails.application.routes.draw do

root :to => 'pages#home'
    get "/" => 'pages#home'
    get '/users/profile' => 'users#profile'
    resources :users, :only => [:index, :show, :new, :create] do
      # TODO: READ ABOUT NESTED ROUTES in RAILS GUIDE
      #this is doing 'read' part of favourites
      get '/favourite_albums' => 'users#favourite_albums'
      get '/favourite_artists' => 'users#favourite_artists'

      #this is doing 'create' part of favourites
      post '/favourite_albums/add' => 'users#add_to_favourite_albums'
      post '/favourite_artists/add' => 'users#add_to_favourite_artists'

      #this is destroy/delete part
      delete '/favourite_albums/:album_id' => 'users#destroy_favourite_album', :as => :favourite_album_destroy

      delete '/favourite_artists/:artist_id' => 'users#destroy_favourite_artist', :as => :favourite_artist_destroy
    end

    # ALBUMS!!
    resources :albums, :only => [:index, :show, :new, :create, :edit, :update, :delete] do
      get '/pressings' => 'pressings#album_index'
    end

    delete '/albums/:id' => 'albums#destroy', :as => :album_destroy

    resources :artists, :only => [:index, :show, :new, :create, :edit, :update, :delete]
    delete '/artists/:id' => 'artists#destroy', :as => :artist_destroy

    resources :pressings, :only => [:index, :show, :new, :create]

  # get 'session/new' #DONT KNOW WHERE THIS CODE CAME FROM?
  # get 'pages/home'
  # get 'users/new'

  #the above line is the same as:::::
    # get '/users/new' => 'users#new'
    # post '/users' => 'users#create'

    get '/login' => 'session#new' #login form
    post '/login' => 'session#create' #perform the login
    delete '/login' => 'session#destroy' #perform signout/'delete' the signin

    get "/search" => 'search#results'

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :bigint(8)        not null, primary key
#  name       :text
#  info       :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ApplicationRecord
  has_many :albums
  has_and_belongs_to_many :users

  include PgSearch
  pg_search_scope :search, against: [:name]
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  #so below they can still view index and show page but not new or create as they're not logged in.
  before_action :check_for_login, :only => [:new, :create]
  def index
  #displaying artists in alphabetical order
    @artists = Artist.all.order(:name)
  end

  def show
    @artist = Artist.find params[:id]
  end

  def new
    @artist = Artist.new
  end

  # def create
  #   # NOTE THIS BELOW DIDNT WORK
  #   artist = Artist.create
  #   artist_params
  #   redirect_to artist_path(artist.id)

    def create
      artist = Artist.create artist_params
      cloudinary = Cloudinary::Uploader.upload( params[ "artist" ][ "image" ] )
      artist.image = cloudinary["url"]
      artist.save
      redirect_to artist
    end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]

    if params[:artist][:image].present?
      cloudinary = Cloudinary::Uploader.upload(params[:artist][:image])
      #replace params image with cloudinary url
      params[:artist][:image]=cloudinary["url"]
    end
    artist.update artist_params
    redirect_to artist
  end

  def destroy
    @artist = Artist.find params[:id]
    @artist.destroy
    redirect_to artists_path
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :image, :info)
  end


end

app/views/artists/_form.html.erb
<div class="form-group">

  <%= form_for @artist do |f| %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => 'form-control', :id => 'exampleFormControlInput1', :required => true %>
</div>

<div class="form-group">
  <%= f.label :info %>
  <%= f.text_area :info, :class => 'form-control', :id => 'exampleFormControlInput1', :required => true %>
</div>

<div class="form-group">
  <%= f.label :image, :class => "label-control" %><br />
  <%= f.file_field :image %>
  <%= image_tag @artist.image, :class => 'teensy' if @artist.image.present? %>
</div>
<%= f.submit %>


  <% end %>

</div>

app/views/artists/edit.html.erb
<div class="album-artist-form">
<h1>Edit Artist</h1>

<%= render :partial => 'form' %>

app/views/artists/index.html.erb
<div class="index-artists-container">
  <h1>All Artists</h1>


<% @artists.each do |artist| %>

  <div class="index-artist-grid">
    <%= link_to image_tag(artist.image, :alt => artist.name, :class => 'artist_thumbnail'), artist if artist.image.present? %>

      <ul>
        <li><%= link_to artist.name, artist  %></li>
        <!-- want to maybe add short part from info and 'hide' rest until/if they click 'read more' -->
      </ul>
  </div>
<% end %>

app/views/artists/new.html.erb
<div class="album-artist-form">
<h1>New Artist</h1>

<%= render :partial => 'form' %>

app/views/artists/show.html.erb
<div class="artist-show">


  <h1><%= @artist.name %></h1>

  <div class="artist-sect">

  <% if @artist.image.present? %>
  <%= image_tag @artist.image, :alt => @artist.name, :class => 'artist_feature' %>

  <br />


  <div class="artist-info">
    <p><%= simple_format @artist.info %></p>
  </div>
</div><!--end of artist sect div-->


  <div class="prev_albums">
      <% @artist.albums.each do |album| %>
      <%= link_to image_tag(album.image, :class => 'album_thumbnail'), album  %>
      <% end %>
  </div><!--end of previous albums div-->
  <% end %>

  <div class="artist-controller">
      <%= link_to 'Add to Favourite Artists', user_favourite_artists_add_path(@current_user, :artist_id => @artist.id), :method => 'post' %> |
    <%= link_to 'edit artist', edit_artist_path(@artist) %>

    <!-- i think the below will make it only visible to admins? -->
    <% if @current_user.admin? %>
    <%= link_to 'delete artist', artist_path(@artist), :method => 'delete', :data => { :confirm => 'Are you sure?'} %>
    <% end %>
  </div>
</div> <!--end of artist show div-->