config/routes.rb
Rails.application.routes.draw do

root :to => 'pages#home'
    get "/" => 'pages#home'
    get '/users/profile' => 'users#profile'
    resources :users, :only => [:index, :show, :new, :create] do
      # TODO: READ ABOUT NESTED ROUTES in RAILS GUIDE
      #this is doing 'read' part of favourites
      get '/favourite_albums' => 'users#favourite_albums'
      get '/favourite_artists' => 'users#favourite_artists'

      #this is doing 'create' part of favourites
      post '/favourite_albums/add' => 'users#add_to_favourite_albums'
      post '/favourite_artists/add' => 'users#add_to_favourite_artists'

      #this is destroy/delete part
      delete '/favourite_albums/:album_id' => 'users#destroy_favourite_album', :as => :favourite_album_destroy

      delete '/favourite_artists/:artist_id' => 'users#destroy_favourite_artist', :as => :favourite_artist_destroy
    end

    # ALBUMS!!
    resources :albums, :only => [:index, :show, :new, :create, :edit, :update, :delete] do
      get '/pressings' => 'pressings#album_index'
    end

    delete '/albums/:id' => 'albums#destroy', :as => :album_destroy

    resources :artists, :only => [:index, :show, :new, :create, :edit, :update, :delete]
    delete '/artists/:id' => 'artists#destroy', :as => :artist_destroy

    resources :pressings, :only => [:index, :show, :new, :create]

  # get 'session/new' #DONT KNOW WHERE THIS CODE CAME FROM?
  # get 'pages/home'
  # get 'users/new'

  #the above line is the same as:::::
    # get '/users/new' => 'users#new'
    # post '/users' => 'users#create'

    get '/login' => 'session#new' #login form
    post '/login' => 'session#create' #perform the login
    delete '/login' => 'session#destroy' #perform signout/'delete' the signin

    get "/search" => 'search#results'

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :text
#  artist_id  :integer
#  date       :date
#  tracks     :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

  include PgSearch
  pg_search_scope :search, against: [:title]

  belongs_to :artist, :optional => true
  has_many :pressings
  has_and_belongs_to_many :users

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :check_for_login, :only => [:new, :create]

  def index #here trying to order albums on index page in alphabetical order
    @albums = Album.all.order(:title)
  end

  def show
    @album = Album.find params[:id]
  end

  def new
    @album = Album.new
  end

  def create
    album = Album.create album_params
    cloudinary = Cloudinary::Uploader.upload( params[ "album" ][ "image" ] )
    album.image = cloudinary["url"]
    album.save
    redirect_to album
  end

  def edit
    @album = Album.find params[:id]
  end

  def update
    album = Album.find params[:id]
    if params[:album][:image].present?
    #upload file
      cloudinary = Cloudinary::Uploader.upload( params[ "album" ][ "image" ] )
      #replace params image with cloudinary url
      params[:album][:image]=cloudinary["url"]
    end
    album.update album_params
    redirect_to album
  end

  def destroy
    album = Album.find params[:id]
    album.destroy
    redirect_to albums_path
  end

  private
  def album_params
    params.require(:album).permit(:title, :artist_id, :date, :tracks, :image) #wasnt sure if i should have included artist id here
  end
end

app/views/albums/_form.html.erb
<div class="form-group">

  <%= form_for @album do |f| %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, :class => 'form-control', :id => 'exampleFormControlInput1' %>
</div>

<div class="form-group">

  <%= f.label :date %>
  <%= f.date_field :date, :class => 'form-control', :id => 'exampleFormControlInput1', :required => true %>
</div>

<div class="form-group">

  <%= f.label :tracks%>
  <%= f.text_area :tracks, :class => "form-control", :id => "exampleFormControlTextarea1" %>
</div>

<div class="form-group">

  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.pluck(:name, :id), :include_blank => true, :class => "form-control", :id => "exampleFormControlSelect1" %>

</div>

<div class="form-group">
  <%= f.label :image, :class =>"label-control" %><br />
  <%= f.file_field :image %>
    <%= image_tag @album.image, :class => 'teensy' if @album.image.present? %>
</div>

  <%= f.submit %>
  <% end %>
</div>

app/views/albums/edit.html.erb
<div class="album-artist-form">
  <h1>Edit Album</h1>

  <%= render :partial => 'form' %>
</div>

app/views/albums/index.html.erb
<div class="index-albums-container">

<h1>All Albums</h1>


  <% @albums.each do |album| %>
    <div class="index-album-grid">

      <%= link_to image_tag(album.image, :alt => album.title, :class => 'album_thumbnail'), album if album.image.present? %>



    <ul>
      <li><%= album.title  %></li>
      <li>Realeased: <%= album.date&.strftime('%e %b %Y') %></li>
      <!-- dont think the line below will work, want to display artist name does work BUT also displays all album info at bottom.  -->

      <% if album.artist.present? %>
        <li>Artist: <%=link_to album.artist.name, album.artist %></li>
        <% else %>
        <br />
      <% end %>
    </ul>
</div> <!-- end of the grid div-->
  <% end %>

app/views/albums/new.html.erb
<div class="album-artist-form">

  <h1>New Album</h1>

  <%= render :partial => 'form' %>
</div>

app/views/albums/show.html.erb
<div class="album-show">

  <h1><%= @album.title %></h1>

  <div class="info-album-show">

    <ul>
      <% if @album.date.present? %>
          <li>Realeased: <%= @album.date&.strftime('%e %b %Y') %></li>
      <% end %>


      <% if @album.artist.present? %>
        <li>Artist: <%= link_to @album.artist.name, @album.artist %></li>
      <% end %>

    </ul>

    <ul>
        <% @album.pressings.each do |pressing| %>
            <li>Pressing: <%= link_to "See pressings", album_pressings_path(@album) %></li>
            <li>Color: <%= pressing.color %></li>
            <li>Pressed in: <%= pressing.year %></li>
          <% if pressing.limited == true %>
            <li>Limited</li>
          <% end %>
          <% if pressing.quantity_pressed.present? %>
            <li>Quantity Pressed: <%= pressing.quantity_pressed %></li>
          <% end %>
          <% if pressing.weight.present? %>
            <li>Weight: <%= pressing.weight %></li>
          <% end %>
        <% end %>

    </ul>

  </div><!--bottom artist show div-->



  <div class="controls">
    <%= link_to 'Add to My Collection', user_favourite_albums_add_path(@current_user, :album_id => @album.id), :method => 'post' %> |


    <%= link_to 'edit album', edit_album_path(@album) %>


    <% if @current_user.admin? %>
      <%= link_to 'delete album', album_path(@album), :method => 'delete', :data => { :confirm => 'Are you sure?'} %>
    <% end %>
  </div><!--end of controlls div-->


  <div class="card">
    <div class="content">

      <div class="front">

        <%= image_tag @album.image, :alt => @album.title, :class => 'album_feature' %>

      </div><!--end of front div-->

      <div class="back">
        <p>Track List: <%= simple_format @album.tracks %>  </p>
      </div><!--end of back div-->

    </div> <!--end of content div -->
  </div><!--end of card div-->

</div><!--end of whole page div-->