config/routes.rb
Rails.application.routes.draw do

root :to => 'pages#home'
    get "/" => 'pages#home'
    get '/users/profile' => 'users#profile'
    resources :users, :only => [:index, :show, :new, :create] do
      # TODO: READ ABOUT NESTED ROUTES in RAILS GUIDE
      #this is doing 'read' part of favourites
      get '/favourite_albums' => 'users#favourite_albums'
      get '/favourite_artists' => 'users#favourite_artists'

      #this is doing 'create' part of favourites
      post '/favourite_albums/add' => 'users#add_to_favourite_albums'
      post '/favourite_artists/add' => 'users#add_to_favourite_artists'

      #this is destroy/delete part
      delete '/favourite_albums/:album_id' => 'users#destroy_favourite_album', :as => :favourite_album_destroy

      delete '/favourite_artists/:artist_id' => 'users#destroy_favourite_artist', :as => :favourite_artist_destroy
    end

    # ALBUMS!!
    resources :albums, :only => [:index, :show, :new, :create, :edit, :update, :delete] do
      get '/pressings' => 'pressings#album_index'
    end

    delete '/albums/:id' => 'albums#destroy', :as => :album_destroy

    resources :artists, :only => [:index, :show, :new, :create, :edit, :update, :delete]
    delete '/artists/:id' => 'artists#destroy', :as => :artist_destroy

    resources :pressings, :only => [:index, :show, :new, :create]

  # get 'session/new' #DONT KNOW WHERE THIS CODE CAME FROM?
  # get 'pages/home'
  # get 'users/new'

  #the above line is the same as:::::
    # get '/users/new' => 'users#new'
    # post '/users' => 'users#create'

    get '/login' => 'session#new' #login form
    post '/login' => 'session#create' #perform the login
    delete '/login' => 'session#destroy' #perform signout/'delete' the signin

    get "/search" => 'search#results'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audiophiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="jquery.js"></script>
    <!-- <script src="vivus.js"></script> -->

  </head>

  <body class="<%= params[:controller] %>-<%= params[:action] %> <%= "logged-in" if @current_user.present? %>">

    <nav>
        <img class="mini-logo" src="/assets/audiophilesgreen.svg" />
    <ul class="nav nav-pills">
      <li class="nav-item">
        <%= link_to 'Home', root_path, :class=> "nav-link" %>
      </li>

      <% if @current_user.present? %>
        <%= link_to 'My Dash', users_profile_path, :class => "nav-link" %>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Artists</a>
        <div class="dropdown-menu">
            <%= link_to 'All Artists', artists_path, :class => "dropdown-item" %>
        <div class="dropdown-menu"></div>
          <%= link_to 'Favourite Artists', user_favourite_artists_path(@current_user), :class => "dropdown-item" %>


          <div class="dropdown-divider"></div>
            <%= link_to 'Add New Artist', new_artist_path, :class => "dropdown-item" %>
        </div>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Albums</a>
          <div class="dropdown-menu">
            <%= link_to 'All Tunes', albums_path, :class => "dropdown-item" %>

            <div class="dropdown-menu"></div>
            <%= link_to 'My Vinyls', user_favourite_albums_path(@current_user), :class => "dropdown-item" %>

            <div class="dropdown-divider"></div>
              <%= link_to 'Add New Album', new_album_path, :class => "dropdown-item" %>
          </div>
      </li>
      <li class="nav-item">
          <%= link_to "Sign Out #{@current_user.username.capitalize} ", login_path, :method => 'delete', :class => "nav-link" %>
      </li>

        <%= link_to 'Admin Area', users_path if @current_user.admin? %>

      <% else %>
      <%= link_to 'Login', login_path, :class => "nav-link" %>
      <%= link_to 'Sign Up', new_user_path, :class => "nav-link" %>
    <% end %>
  </ul>


    </nav>

    <%= yield %>
  </body>
</html>